security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            lazy: true
            provider: app_admin_provider
            custom_authenticator:
                - App\Security\AdminAuthenticator
            logout:
                path: app_admin_logout
                # where to redirect after logout
                # target: app_any_route
            pattern: ^/admin

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /admin/login
                always_remember_me: true
                
        main:
            lazy: true
            provider: app_user_provider
            # custom_authenticator:
            #     - App\Security\UserAuthenticator
            oauth:
                resource_owners:
                    google: /auth/connect/google/check
                login_path: /google/login
                use_forward: false
                failure_path: /login
                oauth_user_provider:
                    service: App\Security\Provider\OAuthServiceProvider
                
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            pattern: ^/

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
