vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'

        packageMedia:
            uri_prefix: /uploads/packages
            upload_destination: '%kernel.project_dir%/public/uploads/packages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer




